In [1]:
import numpy as np
from common import *
from NSpace import *
from XPAlgebra import *
from codes import *


# XP Operator Format
XP operators are generally entered as comma delimited strings.

For calculations, XP operators are represented as integer numpy arrays, and lists of operators are 2D numpy arrays. We transform from the string format using the Str2XP function. This yields the operators in numpy array format as well as the precision of the operators.

We print XP operators by using the XP2Str function.

Use setVerbose(True) to print debugging messages in the code.

In [2]:

setVerbose(True)

## Code 1
genstr = 'XP_8(8|0000000|6554444),XP_8(7|1111111|1241234),XP_8(1|1110000|3134444)'

## Code 2
genstr = 'XP8(0|0000000|1322224)\nXP8(12|1111111|1234567)'

print('Generators input in comma delimited string format')
print(genstr)
G, N = str2XP(genstr)
print('Generators in numpy array format')
print(G)
print('Generators converted back to string format for printing')
print(XP2Str(G,N))

Generators input in comma delimited string format
XP_8(8|0000000|6554444),XP_8(7|1111111|1241234),XP_8(1|1110000|3134444)
Generators in numpy array format
[[8 0 0 0 0 0 0 0 6 5 5 4 4 4 4]
 [7 1 1 1 1 1 1 1 1 2 4 1 2 3 4]
 [1 1 1 1 0 0 0 0 3 1 3 4 4 4 4]]
Generators converted back to string format for printing
XP_8( 8|0000000|6554444)
XP_8( 7|1111111|1241234)
XP_8( 1|1110000|3134444)


# Code Class
XP codes are represented by the code class. To create a new XP code, we pass the generators G in numpy array format, as well as the precision N.

## GetVal Function
Some properties of codes, for instance the Canonical Generators, require some computer time to calculate and are used repeatedly. To calculate store such properties in the code object, we use the getVal function. This function checks if the property has already been calculated - if so it returns the already calculated value; if not it calculates and stores the value for later use.

## Self-Checking Functions
Most functions are "self-checking" - by passing in the result as an optional C value, the function returns True or False depending on whether the value C meets the testing criteria for the function.

## Function Admissible
The function Admissible checks if there are any operators which have fundamental phase not equal to zero.


In [3]:
C = Code(G,N)
S = getVal(C,'S')
print('CanonicalGenerators')
print(XP2Str(S,N))
print('Checking CanonicalGenerators:',CanonicalGenerators(G,N,C=S))
print('Admissible',Admissible(S,N))

CanonicalGenerators
XP_8( 9|1110000|1240000)
XP_8(14|0001111|0001234)
XP_8( 8|0000000|2334444)
XP_8( 0|0000000|0440000)
Checking CanonicalGenerators: True
Admissible True


# Calculating Orbit Representatives $E_m$
Orbit representatives are calculated from the diagonal canonical generators Sz. The steps are as follows:
1. Let li be the list of leading indices of Sx (matrix formed from the X components of the non-diagional canonical generators)
2. Form a matrix Szp from the Z components and phase components of the Sz. For there to be a valid solution, all phase components must be a multiple of 2. We divide the phase components by 2 to ensure they are modulo N (same as the Z component).
3. Determine the kernel modulo N of Szp, K. Remove the last column of K and any zero rows.
4. Use a graph search algorithm to find vectors a such that x = aK mod N is a binary vector. Ensure that entries x[i] = 0 for i in li. 
5. Let A be the matrix formed from the solutions a. Then Em = AK mod N. 

In [4]:

Em = getVal(C,'Em')
print('Em')
print("\n".join(ZMat2str(Em,2)))

li [0, 3]
Szp
23344444
04400000
K
1020000
0130000
0040000
0001000
0000100
0000010
0000001
A
0020000
0020001
0020010
0020011
0020100
0020101
0020110
0020111
Em
0000000
0000001
0000010
0000011
0000100
0000101
0000110
0000111


# Calculating the Code Words
The process for calculating the codewords is:
1. Calculate the Em (see above)
2. Calculate the orbit operator OSx
3. The codeword |k_i> = OSx|m_i> for m_i in Em

In [5]:
CW = getVal(C,'Codewords')
print('Codewords')
for c in CW:
    print(State2Str(c,N))

OSx
XP_8( 0|0000000|0000000)
XP_8( 9|1110000|1240000)
XP_8(14|0001111|0001234)
XP_8( 7|1111111|1241234)
Codewords
w0/16|0000000>+w14/16|0001111>+w9/16|1110000>+w7/16|1111111>
w0/16|0000001>+w6/16|0001110>+w9/16|1110001>+w15/16|1111110>
w0/16|0000010>+w4/16|0001101>+w9/16|1110010>+w13/16|1111101>
w0/16|0000011>+w12/16|0001100>+w9/16|1110011>+w5/16|1111100>
w0/16|0000100>+w2/16|0001011>+w9/16|1110100>+w11/16|1111011>
w0/16|0000101>+w10/16|0001010>+w9/16|1110101>+w3/16|1111010>
w0/16|0000110>+w8/16|0001001>+w9/16|1110110>+w1/16|1111001>
w0/16|0000111>+w0/16|0001000>+w9/16|1110111>+w9/16|1111000>


# Calclating the Core Eq and Lx
To calculate the core Eq, we find the coset decomposition of Em so that Em = Eq + < Lx>. T = < Lx> is the set of binary vectors x such that x + Em = Em:

In [6]:
Eq = getVal(C,'Eq')
print('Eq')
print(ZmatPrint(Eq,2))


T
0000001
0000010
0000011
0000100
0000101
0000110
0000111
Lx is RREF(T)
0000100
0000010
0000001
Eq
0000000
